---
- name: Copy private ssh keys
  copy:
    content: "{{ item.value }}"
    dest: "{{ secrets_directory }}/id_rsa.{{ item.key }}"
    owner: "{{ operator_user }}"
    mode: 0600
  become: true
  with_dict: "{{ private_keys }}"
  no_log: true
