---
- name: Copy AWX environment files
  template:
    src: "env/{{ item }}.env.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}.env"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - awx

- name: Copy AWX configuration files
  template:
    src: "awx/{{ item }}.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - SECRET_KEY
    - credentials.py
    - nginx.conf
    - settings.py

- name: Copy TOWER_PASSWORD secret file
  copy:
    content: "{{ awx_password }}"
    dest: "{{ manager_secrets_directory }}/TOWER_PASSWORD"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"

- name: Copy TOWER_USERNAME secret file
  copy:
    content: "{{ awx_username }}"
    dest: "{{ manager_secrets_directory }}/TOWER_USERNAME"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
