---
- name: Copy AWX environment files
  template:
    src: "env/{{ item }}.env.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}.env"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - awx
    - postgres

- name: Copy AWX configuration files
  template:
    src: "awx/{{ item }}.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - SECRET_KEY
    - credentials.py
    - nginx.conf
    - settings.py
