# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include distribution specific variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages_seed }}"
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  with_items:
    - "{{ ansible_directory }}"
    - "{{ secrets_directory }}"
  become: true

- name: Prepare service
  include: service.yml

- name: Prepare ansible environment
  include: ansible.yml
