---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages_manager }}"
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  with_items:
    - "{{ ansible_directory }}"
    - "{{ archive_directory }}"
    - "{{ secrets_directory }}"
  become: true

- name: manager - include tasks
  include: manager.yml

- name: ansible - include tasks
  include: ansible.yml

- name: wrapper - include tasks
  include: wrapper.yml
