# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include distribution specific variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
    mode: 0700
  with_items:
    - "{{ ansible_roles_path }}"
    - "{{ cache_directory }}"
    - "{{ logs_directory }}"
    - "{{ secrets_directory }}"
  become: true

- name: Copy roles requirements file
  template:
    src: requirements.yml.j2
    dest: "{{ ansible_roles_path }}/requirements.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
    mode: 0600

- name: Download private role tarballs
  get_url:
    url: "https://{{ nexus_server }}/repository/{{ nexus_roles_repository }}/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ ansible_roles_path}}/{{ item.name }}.tar.gz"
    mode: 0644
    url_username: "{{ nexus_username }}"
    url_password: "{{ nexus_password }}"
    force_basic_auth: yes
  with_items: "{{ nexus_roles }}"
  ignore_errors: yes

- name: Create directory for virtual environment
  file:
    path: "{{ venv_directory }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
    state: directory
    mode: 0750
  become: true

- name: Upgrade pip package
  pip:
    name: pip
    state: latest
    virtualenv: "{{ venv_directory }}"
  become: ansible_os_family == 'RedHat'

- name: Install required packages in virtual environment
  shell: |
    source "{{ venv_directory }}/bin/activate"
    pip install {{ item }}
  args:
    executable: /bin/bash
  become: ansible_os_family == 'RedHat'
  with_items: "{{ python_requirements }}"

- name: Install required ansible roles
  shell: |
    source {{ venv_directory }}/bin/activate
    ansible-galaxy install -f --ignore-errors -r {{ ansible_roles_path }}/requirements.yml
  args:
    executable: /bin/bash

- name: Set system wide settings in profile file
  blockinfile:
    dest: /etc/profile.d/ansbile.sh
    marker: "# {mark} ANSIBLE MANAGED BLOCK (betacloud.seed)"
    block: |
      source {{ venv_directory }}/bin/activate
      export PS1='(ansible) \t \u@\H \W $ '
    create: yes
  become: true

- name: Remove private role tarballs
  file:
    path: "{{ ansible_roles_path}}/{{ item.name }}.tar.gz"
    state: absent
  with_items: "{{ nexus_roles }}"

- name: Copy private SSH key
  copy:
    content: "{{ kolla_private_key }}"
    dest: "{{ secrets_directory }}/id_rsa.kolla"
    owner: "{{ operator_user }}"
    mode: 0600
  become: true
