# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include distribution specific variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
    mode: 0750
  with_items:
    - "{{ ansible_roles_directory }}"
    - "{{ cache_directory }}"
    - "{{ logs_directory }}"
    - "{{ secrets_directory }}"
  become: true

- name: Copy roles requirements file
  template:
    src: requirements.yml.j2
    dest: "{{ ansible_roles_directory }}/requirements.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
    mode: 0600

- name: Download private role tarballs
  get_url:
    url: "https://{{ nexus_server }}/repository/{{ nexus_roles_repository }}/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ ansible_roles_directory }}/{{ item.name }}.tar.gz"
    mode: 0644
    url_username: "{{ nexus_username }}"
    url_password: "{{ nexus_password }}"
    force_basic_auth: yes
  with_items: "{{ nexus_roles }}"
  ignore_errors: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  become: true

- name: Install required python packages
  shell: |
    pip install '{{ item }}'
  args:
    executable: /bin/bash
  with_items: "{{ python_requirements }}"
  become: true

- name: Install required ansible roles
  shell: |
    ansible-galaxy install -f --ignore-errors -r {{ ansible_roles_directory }}/requirements.yml -p {{ ansible_roles_directory }}
  args:
    executable: /bin/bash

- name: Remove private role tarballs
  file:
    path: "{{ ansible_roles_directory }}/{{ item.name }}.tar.gz"
    state: absent
  with_items: "{{ nexus_roles }}"

- name: Copy private SSH key
  copy:
    content: "{{ kolla_private_key }}"
    dest: "{{ secrets_directory }}/id_rsa.kolla"
    owner: "{{ operator_user }}"
    mode: 0600
  become: true
