# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include distribution specific variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_user }}"
    mode: 0700
  with_items:
    - "{{ ansible_roles_path }}"
    - "{{ cache_directory }}"
    - "{{ logs_directory }}"
    - "{{ secrets_directory }}"
  become: true

- name: Download private role tarballs
  get_url:
    url: "https://{{ nexus_server }}/repository/{{ nexus_roles_repository }}/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ ansible_roles_path}}/{{ item.name }}.tar.gz"
    mode: 0644
    url_username: "{{ nexus_username }}"
    url_password: "{{ nexus_password }}"
    force_basic_auth: yes
  with_items: "{{ nexus_roles }}"

- name: Create directory for virtual environment
  file:
    path: "{{ venv_directory }}"
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0750
  become: true

- name: Check if requirements file exists
  stat:
    path: "{{ configuration_directory }}/requirements.txt"
  register: stat_requirements_file

- name: Install requirements in virtual environment
  pip:
    requirements: "{{ configuration_directory }}/requirements.txt"
    virtualenv: "{{ venv_directory }}"
  when: stat_requirements_file.stat.exists

- name: Install required roles
  shell: |
    source {{ venv_directory }}/bin/activate
    ansible-galaxy install -f --ignore-errors -r roles/roles-{{ item }}.yml
  args:
    executable: /bin/bash
    chdir: "{{ configuration_directory }}"
  with_items:
    - private
    - public

- name: Check if distribution specific roles file exists
  stat:
    path: "{{ configuration_directory }}/roles/roles-{{ ansible_os_family }}.yml"
  register: stat_distribution_role_file

- name: Install distribution specific roles
  shell: |
    source {{ venv_directory }}/bin/activate
    ansible-galaxy install -f --ignore-errors -r roles/roles-{{ ansible_os_family }}.yml
  args:
    executable: /bin/bash
    chdir: "{{ configuration_directory }}"
  when: stat_distribution_role_file.stat.exists

- name: Install xenserver specific role
  shell: |
    source {{ venv_directory }}/bin/activate
    ansible-galaxy install -f --ignore-errors -r roles/roles-xenserver.yml
  args:
    executable: /bin/bash
    chdir: "{{ configuration_directory }}"
  when: "'xenserver' in group_names"

- name: Set system wide settings in profile file
  blockinfile:
    dest: /etc/profile.d/ansbile.sh
    marker: "# {mark} ANSIBLE MANAGED BLOCK (betacloud.seed)"
    block: |
      source {{ venv_directory }}/bin/activate
      export PS1='(ansible) \t \u@\H \W $ '
    create: yes
  become: true

- name: Remove private role tarballs
  file:
    path: "{{ ansible_roles_path}}/{{ item.name }}.tar.gz"
    state: absent
  with_items: "{{ nexus_roles }}"

- name: Copy private SSH key
  copy:
    content: "{{ kolla_private_key }}"
    dest: "{{ secrets_directory }}/id_rsa.kolla"
    owner: "{{ operator_user }}"
    mode: 0600
  become: true
