---
- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ manager_docker_compose_directory }}"
    - "{{ manager_configuration_directory }}"

- name: Copy environment files required by ARA
  template:
    src: "env/{{ item }}.env.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}.env"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - ara
    - ara-server
    - mariadb
  when: ara_enable|bool

- name: Copy environment files required by AWX
  template:
    src: "env/{{ item }}.env.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}.env"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - awx
    - postgres
  when: awx_enable|bool

- name: Copy configuration files required by AWX
  template:
    src: "awx/{{ item }}.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - SECRET_KEY
    - credentials.py
    - nginx.conf
    - settings.py
    - tower_cli.cfg
  when: awx_enable|bool

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ manager_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: Pull images
  command: "docker-compose -f {{ manager_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: Run service
  command: "docker-compose -f {{ manager_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
