---
- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    ansible_ssh_user: dragon

    awx_enable: true
    awx_vault_type: vault

    netbox_enable: true

  roles:
    - role: ansible-manager
